use anyhow::Result;
use nexus_core::{ClusterPlan, PlanDocument};

pub fn render_markdown(plan: &PlanDocument) -> Result<String> {
    let mut out = String::new();
    out.push_str("# Nexus Report\n\n");
    out.push_str(&format!(
        "- Generated at: {}\n- Generated by: {}\n- Cluster count: {}\n\n",
        plan.generated_at.to_rfc3339(),
        plan.generated_by,
        plan.clusters.len()
    ));

    for cluster_plan in &plan.clusters {
        render_cluster(&mut out, cluster_plan);
    }

    Ok(out)
}

fn render_cluster(out: &mut String, cluster_plan: &ClusterPlan) {
    let cluster = &cluster_plan.cluster;

    out.push_str(&format!("## {}\n\n", cluster.label));
    out.push_str(&format!(
        "- Cluster ID: `{}`\n- Status: `{:?}`\n- Confidence: `{:.2}`\n- Canonical clone: `{}`\n- Canonical remote: `{}`\n\n",
        cluster.id,
        cluster.status,
        cluster.confidence,
        cluster.canonical_clone_id.as_deref().unwrap_or("none"),
        cluster.canonical_remote_id.as_deref().unwrap_or("none")
    ));

    out.push_str("### Scores\n\n");
    out.push_str(&format!(
        "- Canonical: `{:.1}`\n- Usability: `{:.1}`\n- OSS readiness: `{:.1}`\n- Risk: `{:.1}`\n\n",
        cluster.scores.canonical,
        cluster.scores.usability,
        cluster.scores.oss_readiness,
        cluster.scores.risk
    ));

    out.push_str("### Evidence\n\n");
    if cluster.evidence.is_empty() {
        out.push_str("- none\n\n");
    } else {
        for ev in &cluster.evidence {
            out.push_str(&format!(
                "- `{}` `{:+.1}` — {}\n",
                ev.kind, ev.score_delta, ev.detail
            ));
        }
        out.push('\n');
    }

    out.push_str("### Actions\n\n");
    if cluster_plan.actions.is_empty() {
        out.push_str("- none\n\n");
    } else {
        for action in &cluster_plan.actions {
            out.push_str(&format!(
                "- `{:?}` `{:?}` target=`{}` — {}\n",
                action.priority, action.action_type, action.target_id, action.reason
            ));
        }
        out.push('\n');
    }
}
