use anyhow::Result;
use chrono::{DateTime, Utc};
use gittriage_core::{
    ClusterPlan, ClusterRecord, ClusterScope, ClusterScopeFilter, ClusterStatus, PlanDocument,
};

/// Backward-compatible alias ([`ClusterScopeFilter`]).
pub type ReportScopeFilter = ClusterScopeFilter;

/// Optional inventory / DB context lines in the markdown header.
#[derive(Debug, Clone, Default)]
pub struct ReportExtras {
    pub scope_filter: Option<ClusterScopeFilter>,
    /// When [`Self::scope_filter`] is set, the cluster count before filtering (for the header).
    pub unfiltered_cluster_count: Option<usize>,
    pub local_only_count: usize,
    pub mixed_count: usize,
    pub remote_only_count: usize,
    pub empty_count: usize,
    /// When true and no scope filter, group clusters under local-first section headings.
    pub prefer_local_involved_sections: bool,
    pub latest_scan_started_at: Option<DateTime<Utc>>,
    /// When `None`, omit SQLite persistence lines (library-only / tests). When `Some`, document DB plan rows.
    pub sqlite_persisted: Option<(u64, Option<DateTime<Utc>>)>,
    pub skipped_nested_git_paths: Vec<String>,
}

/// Count clusters by [`ClusterScope`] (member-kind buckets).
pub fn scope_breakdown(plan: &PlanDocument) -> (usize, usize, usize, usize) {
    let mut local_only = 0usize;
    let mut mixed = 0usize;
    let mut remote_only = 0usize;
    let mut empty = 0usize;
    for cp in &plan.clusters {
        match cp.cluster.cluster_scope() {
            ClusterScope::LocalOnly => local_only += 1,
            ClusterScope::Mixed => mixed += 1,
            ClusterScope::RemoteOnly => remote_only += 1,
            ClusterScope::Empty => empty += 1,
        }
    }
    (local_only, mixed, remote_only, empty)
}

pub fn filter_plan_by_scope(
    plan: &PlanDocument,
    filter: Option<ClusterScopeFilter>,
) -> PlanDocument {
    let Some(f) = filter else {
        return plan.clone();
    };
    let clusters: Vec<ClusterPlan> = plan
        .clusters
        .iter()
        .filter(|cp| f.matches(cp.cluster.cluster_scope()))
        .cloned()
        .collect();
    PlanDocument {
        clusters,
        ..plan.clone()
    }
}

pub fn render_markdown(plan: &PlanDocument) -> Result<String> {
    let (l, m, r, e) = scope_breakdown(plan);
    render_markdown_with(
        plan,
        ReportExtras {
            local_only_count: l,
            mixed_count: m,
            remote_only_count: r,
            empty_count: e,
            ..Default::default()
        },
    )
}

pub fn render_markdown_with(plan: &PlanDocument, extras: ReportExtras) -> Result<String> {
    let mut out = String::new();
    out.push_str("# GitTriage Report\n\n");
    let shown = plan.clusters.len();
    if let Some(total) = extras.unfiltered_cluster_count {
        out.push_str(&format!(
            "- Generated at: {}\n- Generated by: {}\n- Cluster count (shown): {} (of {} total)\n",
            plan.generated_at.to_rfc3339(),
            plan.generated_by,
            shown,
            total
        ));
        if let Some(f) = extras.scope_filter {
            out.push_str(&format!(
                "- Scope filter: `{}` (see `gittriage report --scope`)\n",
                scope_filter_label(f)
            ));
        }
    } else {
        out.push_str(&format!(
            "- Generated at: {}\n- Generated by: {}\n- Cluster count: {}\n",
            plan.generated_at.to_rfc3339(),
            plan.generated_by,
            shown
        ));
    }

    let local_involved = extras.local_only_count + extras.mixed_count;
    out.push_str(&format!(
        "- **Local triage focus:** {} cluster(s) involve a local checkout ({} local-only + {} mixed); {} remote-only",
        local_involved,
        extras.local_only_count,
        extras.mixed_count,
        extras.remote_only_count
    ));
    if extras.empty_count > 0 {
        out.push_str(&format!(", {} empty (no members)", extras.empty_count));
    }
    out.push('\n');

    out.push_str(&format!(
        "- Clusters by member scope: {} local-only, {} mixed, {} remote-only",
        extras.local_only_count, extras.mixed_count, extras.remote_only_count
    ));
    if extras.empty_count > 0 {
        out.push_str(&format!(", {} empty (no members)", extras.empty_count));
    }
    out.push('\n');

    out.push_str(
        "- _Plan body is recomputed from the current inventory (same engine as `plan` / `score`, not necessarily the last `plan --write` JSON on disk)._\n",
    );

    if let Some(ts) = extras.latest_scan_started_at {
        out.push_str(&format!(
            "- Latest inventory scan started: {}\n",
            ts.to_rfc3339()
        ));
    }

    if let Some((n_persist, persist_at)) = extras.sqlite_persisted {
        if n_persist == 0 {
            out.push_str("- SQLite persisted plan rows: **none** — `scan` clears them; run `gittriage plan` if you need a persisted DB plan (e.g. before relying on other tools).\n");
        } else if let Some(ts) = persist_at {
            out.push_str(&format!(
                "- SQLite persisted plan: **{n_persist}** cluster row(s), last updated {}\n",
                ts.to_rfc3339()
            ));
            if let Some(scan_ts) = extras.latest_scan_started_at {
                if ts < scan_ts {
                    out.push_str("- _Note: SQLite plan timestamp is **older** than the latest scan start — the report body still uses a fresh in-memory plan from inventory; run `gittriage plan` to refresh persisted rows._\n");
                }
            }
        }
    }

    out.push('\n');

    render_skipped_nested_section(&mut out, &extras.skipped_nested_git_paths);
    render_plan_warnings(&mut out, plan);

    let use_sections = extras.prefer_local_involved_sections
        && extras.scope_filter.is_none()
        && should_split_local_sections(plan);

    if use_sections {
        let (local, remote, empty) = partition_by_scope(plan);
        out.push_str("## Clusters with local checkouts\n\n");
        out.push_str(
            "_These clusters include at least one inventoried local clone — prioritize for filesystem cleanup._\n\n",
        );
        for cp in local {
            render_cluster(&mut out, cp);
        }
        if !remote.is_empty() {
            out.push_str("## Remote-only clusters\n\n");
            out.push_str(
                "_No local clone in this cluster (GitHub/catalog rows only). Lower priority for local disk cleanup._\n\n",
            );
            for cp in remote {
                render_cluster(&mut out, cp);
            }
        }
        if !empty.is_empty() {
            out.push_str("## Clusters with no members\n\n");
            for cp in empty {
                render_cluster(&mut out, cp);
            }
        }
    } else {
        for cluster_plan in &plan.clusters {
            render_cluster(&mut out, cluster_plan);
        }
    }

    Ok(out)
}

fn should_split_local_sections(plan: &PlanDocument) -> bool {
    let mut has_local = false;
    let mut has_remote = false;
    for cp in &plan.clusters {
        match cp.cluster.cluster_scope() {
            ClusterScope::LocalOnly | ClusterScope::Mixed => has_local = true,
            ClusterScope::RemoteOnly => has_remote = true,
            ClusterScope::Empty => {}
        }
    }
    has_local && has_remote
}

fn partition_by_scope(
    plan: &PlanDocument,
) -> (Vec<&ClusterPlan>, Vec<&ClusterPlan>, Vec<&ClusterPlan>) {
    let mut local = Vec::new();
    let mut remote = Vec::new();
    let mut empty = Vec::new();
    for cp in &plan.clusters {
        match cp.cluster.cluster_scope() {
            ClusterScope::LocalOnly | ClusterScope::Mixed => local.push(cp),
            ClusterScope::RemoteOnly => remote.push(cp),
            ClusterScope::Empty => empty.push(cp),
        }
    }
    let sort_key = |a: &&ClusterPlan, b: &&ClusterPlan| {
        a.cluster
            .label
            .to_lowercase()
            .cmp(&b.cluster.label.to_lowercase())
    };
    local.sort_by(sort_key);
    remote.sort_by(sort_key);
    empty.sort_by(sort_key);
    (local, remote, empty)
}

fn scope_filter_label(f: ClusterScopeFilter) -> &'static str {
    match f {
        ClusterScopeFilter::LocalOnly => "local-only",
        ClusterScopeFilter::Mixed => "mixed",
        ClusterScopeFilter::RemoteOnly => "remote-only",
    }
}

fn render_skipped_nested_section(out: &mut String, paths: &[String]) {
    if paths.is_empty() {
        return;
    }
    out.push_str("## Skipped nested git repositories\n\n");
    out.push_str(
        "_These paths contain a `.git` directory inside another scanned root; they were not inventoried because `scan.include_nested_git` is false. Enable it in `gittriage.toml` to include them._\n\n",
    );
    for p in paths {
        out.push_str(&format!("- `{}`\n", p));
    }
    out.push('\n');
}

fn render_plan_warnings(out: &mut String, plan: &PlanDocument) {
    let mut lines: Vec<String> = Vec::new();
    for cp in &plan.clusters {
        let c = &cp.cluster;
        if matches!(
            c.status,
            ClusterStatus::Ambiguous | ClusterStatus::ManualReview
        ) {
            lines.push(format!(
                "- **{}** (`{}`): status `{:?}` — treat canonical choice as **tentative** until you verify remotes and local-only work.",
                c.label, c.id, c.status
            ));
        } else if c.confidence < 0.6 {
            lines.push(format!(
                "- **{}** (`{}`): confidence `{:.2}` — below the usual resolved threshold; double-check evidence before acting.",
                c.label, c.id, c.confidence
            ));
        }
    }
    if lines.is_empty() {
        return;
    }
    out.push_str("## Warnings\n\n");
    out.push_str(
        "_These clusters need extra human judgment; GitTriage does not mutate repos automatically._\n\n",
    );
    for line in lines {
        out.push_str(&line);
        out.push('\n');
    }
    out.push('\n');
}

fn render_cluster(out: &mut String, cluster_plan: &ClusterPlan) {
    let cluster = &cluster_plan.cluster;

    out.push_str(&format!("## {}\n\n", cluster.label));
    let scope = cluster.cluster_scope();
    out.push_str(&format!(
        "- Cluster ID: `{}`\n- Status: `{:?}`\n- Confidence: `{:.2}`\n- Member scope: `{:?}`\n- Canonical clone: `{}`\n- Canonical remote: `{}`\n\n",
        cluster.id,
        cluster.status,
        cluster.confidence,
        scope,
        cluster.canonical_clone_id.as_deref().unwrap_or("none"),
        cluster.canonical_remote_id.as_deref().unwrap_or("none")
    ));

    out.push_str("### Scores\n\n");
    out.push_str(&format!(
        "- Canonical confidence: `{:.1}` (`scores.canonical`)\n- Repo health: `{:.1}` (`scores.usability`)\n- Recoverability: `{:.1}` (`scores.recoverability`)\n- Publish readiness: `{:.1}` (`scores.oss_readiness`)\n- Maintenance risk: `{:.1}` (`scores.risk`)\n\n",
        cluster.scores.canonical,
        cluster.scores.usability,
        cluster.scores.recoverability,
        cluster.scores.oss_readiness,
        cluster.scores.risk
    ));

    render_score_explanations(out, cluster);

    out.push_str("### Evidence\n\n");
    if cluster.evidence.is_empty() {
        out.push_str("- _(none — unexpected; file an issue if reproducible)_\n\n");
    } else {
        for ev in &cluster.evidence {
            out.push_str(&format!(
                "- `{}` `{:+.1}` — {}\n",
                ev.kind, ev.score_delta, ev.detail
            ));
        }
        out.push('\n');
    }

    out.push_str("### Actions\n\n");
    if cluster_plan.actions.is_empty() {
        out.push_str("- none\n\n");
    } else {
        for action in &cluster_plan.actions {
            out.push_str(&format!(
                "- `{:?}` `{:?}` target=`{}` — {}\n",
                action.priority, action.action_type, action.target_id, action.reason
            ));
            if let Some(ref s) = action.evidence_summary {
                out.push_str(&format!("  - Evidence: {s}\n"));
            }
            if let Some(c) = action.confidence {
                out.push_str(&format!("  - Action confidence: `{c:.2}`\n"));
            }
            if let Some(ref r) = action.risk_note {
                out.push_str(&format!("  - Risk / trade-off: {r}\n"));
            }
        }
        out.push('\n');
    }
}

/// Deterministic copy that ties headline numbers to the evidence list (always emitted).
fn render_score_explanations(out: &mut String, cluster: &ClusterRecord) {
    out.push_str("### Score explanations\n\n");
    out.push_str(&format!(
        "- **Canonical confidence (`{:.1}`):** reflects remote URL agreement, clone freshness, git metadata, and optional `merge_base` lines in Evidence below.\n",
        cluster.scores.canonical
    ));
    out.push_str(&format!(
        "- **Repo health (`{:.1}`):** reflects manifest/readme signals and similar scan-time cues (`manifest_present`, `readme_present`, …).\n",
        cluster.scores.usability
    ));
    out.push_str(&format!(
        "- **Recoverability (`{:.1}`):** reflects git metadata, remote linkage, recency, and worktree state (`git_object_db`, `remote_backup_path`, `clean_worktree_recover`, …).\n",
        cluster.scores.recoverability
    ));
    out.push_str(&format!(
        "- **Publish readiness (`{:.1}`):** reflects license and GitHub metadata heuristics—not a full OSS audit (`license_present`, remote fork/archived flags, …).\n",
        cluster.scores.oss_readiness
    ));
    out.push_str(&format!(
        "- **Maintenance risk (`{:.1}`):** higher when clusters are ambiguous, duplicated, or missing remotes (`multiple_clones`, `ambiguous_cluster`, …).\n\n",
        cluster.scores.risk
    ));
}
